# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build & test .NET app

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore MomentumF.sln
      
    - name: Build
      run: dotnet build src/MomentumCalculator.CLI/MomentumF.csproj
      
    - name: Testg
      id: tests
      run: |
      chmod +x tests/scripts/run-test-suite.sh
      ./tests/scripts/run-test-suite.sh
      continue-on-error: true

    - name: Check Results
      run: |
      if [ ${{ steps.tests.outputs.exit_code }} -eq 2 ]; then
      echo "Catastr√≥fico: Todos los tests fallaron"
      fi
      
    - name: Build (Release)
      run: dotnet build --configuration Release --no-restore
